# 作业2：纯天然手工制作神经网络

本次作业中，你将体验到如何用最基本的矩阵运算来实现一个前馈神经网络。在该实现中，唯一需要使用到的软件包是Numpy。

### 第1题

利用 Git 的基本操作，对第一次作业进行一次修订。具体要求如下：

1. 将库的名称统一为 “ai2021s”。
2. 在库的根目录创建文件夹 `HW1`，将第一次作业提交的 Notebook 文件重命名为 `numpy_practice.ipynb`，并移至 `HW1` 文件夹中。
3. 提交这一修改，提交信息为 “reorganizing project files”。
4. 从本次作业起，均按上述规则建立文件夹。本次作业的文件名为`fnn.ipynb`。
5. 优化作业1中各函数的编写，直接对原始文件修改并利用 Git 命令提交。根据本次修改的结果，你将对作业1获得最多20分的加分。

### 第2题

(a) 根据作业1的内容，编写**数值稳定**的函数 `sigmoid(x)` 和 `softplus(x)`，要求它适用于 Numpy 向量和矩阵，即当 `x` 是一维或二维数组时，返回一个相同大小和形状的数组。

In [78]:
import numpy as np
np.set_printoptions(linewidth=100) 

def sigmoid(x):
    res = np.zeros_like(x)
    res = np.where(x>0,1/np.exp(-x),np.exp(x)/(np.exp(x)+1))
    return res


def softplus(x):
    res = np.zeros_like(x)
    res = np.where(x>0,np.log(1+np.exp(-x))+x,np.log(1+np.exp(x)))
    return res

np.random.seed(123)
vec = np.random.normal(size=6)
mat = np.random.normal(size=(5, 3))
print("Sigmoid(v) =\n", sigmoid(vec))
print("Sigmoid(m) =\n", sigmoid(mat))
print("Softplus(v) =\n", softplus(vec))
print("Softplus(m) =\n", softplus(mat))

Sigmoid(v) =
 [0.25244196 2.71107557 1.32707663 0.18148857 0.35925474 5.21446522]
Sigmoid(m) =
 [[0.08116076 0.39438602 3.54641154]
 [0.29593301 0.33650995 0.47634044]
 [4.44326571 0.34549479 0.39079256]
 [0.39308777 9.07869158 8.90654223]
 [2.72932383 1.47135891 2.09042747]]
Softplus(v) =
 [0.29094333 1.31132175 0.84461281 0.20026791 0.44512331 1.82687967]
Softplus(m) =
 [[0.08464411 0.50151249 1.51433825]
 [0.35088177 0.41024142 0.6469135 ]
 [1.69437919 0.42387573 0.49559644]
 [0.49937109 2.31042345 2.29319537]
 [1.31622694 0.90476816 1.12830942]]


(b) 推导 Sigmoid 和 Softplus 函数的导数，编写**数值稳定**的函数 `d_sigmoid(x)` 和 `d_softplus(x)` 计算对应的导数，同样要求适用于向量和矩阵。

$\sigma(x)=1/(1+\exp(-x)),\ \sigma'(x)=...$

$\mathrm{softplus}(x)=\log(1+\exp(x)),\ \mathrm{softplus}'(x)=...$

注意到 Sigmoid 和 Softplus 之间的联系了吗？

In [79]:
def d_sigmoid(x):
    res = np.zeros_like(x)
    res = np.where(x>0,np.exp(-x)/(1+np.exp(-x))**2,np.exp(x)/((np.exp(x))**2+2*np.exp(x)+1))
    return res

def d_softplus(x):
    res = np.zeros_like(x)
    res = np.where(x>0,1/(1+np.exp(-x)),np.exp(x)/(np.exp(x)+1))
    return res

print("Sigmoid'(v) =\n", d_sigmoid(vec))
print("Sigmoid'(m) =\n", d_sigmoid(mat))
print("Softplus'(v) =\n", d_softplus(vec))
print("Softplus'(m) =\n", d_softplus(mat))

Sigmoid'(v) =
 [0.18871502 0.196853   0.24506124 0.14855047 0.23019077 0.13502129]
Sigmoid'(m) =
 [[0.07457369 0.23884569 0.17157406]
 [0.20835666 0.223271   0.24944023]
 [0.14996269 0.22612814 0.23807373]
 [0.23856977 0.08937477 0.09075383]
 [0.19624332 0.24090565 0.21887592]]
Softplus'(v) =
 [0.25244196 0.73053634 0.57027629 0.18148857 0.35925474 0.83908511]
Softplus'(m) =
 [[0.08116076 0.39438602 0.78004631]
 [0.29593301 0.33650995 0.47634044]
 [0.81628676 0.34549479 0.39079256]
 [0.39308777 0.90078077 0.89905661]
 [0.73185488 0.59536432 0.67642017]]


(c) 编写函数 `relu(x)` 和 `d_relu(x)` 来实现 ReLU 函数及其导数，$\mathrm{ReLU}(x)=\max(x,0)$，要求适用于向量和矩阵。对于不可导的点，可以将导数取为左导数或右导数。

In [80]:
def relu(x):
    res = np.zeros_like(x)
    res = np.where(x>0,x,0)
    return res

def d_relu(x):
    res = np.zeros_like(x)
    res = np.where(x>0,1,0)
    return res

print("ReLU(v) =\n", relu(vec))
print("ReLU(m) =\n", relu(mat))
print("ReLU'(v) =\n", d_relu(vec))
print("ReLU'(m) =\n", d_relu(mat))

ReLU(v) =
 [0.         0.99734545 0.2829785  0.         0.         1.65143654]
ReLU(m) =
 [[0.         0.         1.26593626]
 [0.         0.         0.        ]
 [1.49138963 0.         0.        ]
 [0.         2.20593008 2.18678609]
 [1.0040539  0.3861864  0.73736858]]
ReLU'(v) =
 [0 1 1 0 0 1]
ReLU'(m) =
 [[0 0 1]
 [0 0 0]
 [1 0 0]
 [0 1 1]
 [1 1 1]]


### 第3题

练习标量的反向传播算法。考虑一个两层的前馈神经网络（见第5周课件107页），其中数据和权重都是标量：

![](img/model1.png)

如下为正向的计算过程：

In [81]:
x = 1.2345
w1 = 0.111
b1 = 0.222
w2 = 0.333
b2 = -0.444

a0 = x
z1 = w1 * a0 + b1
a1 = sigmoid(z1)
z2 = w2 * a1 + b2
a2 = z2

yhat = a2
y = 5.4321

令损失函数为 $l=(y-\hat{y})^2$，则可以计算出 $l$ 对 $a_2=\hat{y}$ 的导数为 $\mathrm{d}l/\mathrm{d}a_2=2(a_2-y)$：

In [82]:
d_l_a2 = 2.0 * (a2 - y) # This is the "upstream derivative" associated with a2

现在将 $a_2$ 的导数反向传播给 $z_2$。首先计算 $a_2$ 对 $z_2$ 的“局部导数”：因为 $a_2=z_2$，所以局部导数为1。然后将“上游导数”乘以“局部导数”，即得到“下游导数”。

In [83]:
d_a2_z2 = 1.0 # The "local derivative" of a2 with respect to z2
d_l_z2 = d_l_a2 * d_a2_z2 # The "downstream derivative" of l with respect to z2

print(d_l_z2)

-10.798528597261857


接下来将 $z_2$ 的导数继续向下游传播。在上一层的计算中得到的“下游导数”现在变成了“上游导数”，进而向 $a_1$、$w_2$ 和 $b_2$ 传播。依然进行局部导数的计算，可以得到 $\mathrm{d}z_2/\mathrm{d}a_1=w_2$, $\mathrm{d}z_2/\mathrm{d}w_2=a_1$, $\mathrm{d}z_2/\mathrm{d}b_2=1$。

In [84]:
d_z2_a1 = w2
d_z2_w2 = a1
d_z2_b2 = 1.0

于是通过链式法则，将“上游导数”乘以“局部导数”得到“下游导数”。

In [85]:
d_l_a1 = d_l_z2 * d_z2_a1
d_l_w2 = d_l_z2 * d_z2_w2
d_l_b2 = d_l_z2 * d_z2_b2

print(d_l_a1)
print(d_l_w2)
print(d_l_b2)

-3.5959100228881984
-15.462834706995
-10.798528597261857


请完成后续的过程，计算出 $\mathrm{d}l/\mathrm{d}w_1$ 和 $\mathrm{d}l/\mathrm{d}b_1$。

```py
d_l_w1 = ...
d_l_b1 = ...

print(d_l_w1)
print(d_l_b1)
```

In [86]:
d_a1_z1 = a1*(1-a1)
d_l_z1 =d_l_a1 * d_a1_z1
print(d_l_z1)

2.2241076752346496


In [87]:
d_z1_w1 = x
d_z1_b1 = 1
d_l_w1 = d_l_z1 * d_z1_w1
d_l_b1 = d_l_z1 *d_z1_b1
print(d_l_w1)
print(d_l_b1)

2.745660925077175
2.2241076752346496


### 第4题

现在考虑一个更实际的场景，首先，数据包含多个观测，每个观测占据一行：

In [88]:
x = np.array([[0.0, 0.0],
              [0.0, 1.0],
              [1.0, 0.0],
              [1.0, 1.0]])
y = np.array([[0.0],
              [1.0],
              [1.0],
              [0.0]])

可以看出输入的维度为 $p=2$，输出的维度为 $d=1$，样本量为 $n=4$。我们将构建一个两层的前馈神经网络，其中隐藏层的维度为 $r=5$。计算流程如下：

![](img/model2.png)

$Z_1=XW_1+\mathbf{1}_nb_1^T,\quad A_1=\mathrm{softplus}(Z_1)$

$Z_2=A_1W_2+\mathbf{1}_nb_2^T,\quad A_2=\mathrm{sigmoid}(Z_2)$

其中 $\mathbf{1}_n$ 为元素全为1的 $n\times 1$ 向量，$W_1$ 为 $p\times r$ 矩阵，$b_1$ 为 $r\times 1$ 向量，$W_2$ 为 $r\times d$ 矩阵，$b_2$ 为 $d\times 1$ 向量。

In [89]:
p = 2
d = 1
n = 4
r = 5

np.random.seed(123)
w1 = np.random.normal(size=(p, r))
b1 = np.random.normal(size=(r, 1))
w2 = np.random.normal(size=(r, d))
b2 = np.random.normal(size=(d, 1))

a0 = x
ones = np.ones((n, 1))
z1 = a0.dot(w1) + ones.dot(b1.T)
a1 = softplus(z1)
z2 = a1.dot(w2) + ones.dot(b2.T)
a2 = sigmoid(z2)

phat = a2
print(phat)

[[ 549.1969833 ]
 [  87.369357  ]
 [2599.97309354]
 [ 115.14603531]]


定义第 $i$ 个观测的损失函数为 $l(y_i,\hat{p}_i)=-y_i \cdot \log(\hat{p}_i)-(1-y_i) \cdot \log(1-\hat{p}_i)$，请推导出 $l$ 对 $\hat{p}_i$ 的导数。

$\mathrm{d}l/\mathrm{d}\hat{p}_i=(\hat{p}_i-y_i)/(\hat{p}_i(1-\hat{p}_i))$

定义整体的损失函数为 $L(y,\hat{p})=n^{-1}\sum_{i=1}^n l(y_i,p_i)$，请给出 $L$ 对 $\hat{p}_i$ 的导数。

$\mathrm{d}L/\mathrm{d}\hat{p}_i=n^{-1}(\hat{p}_i-y_i)/(\hat{p}_i(1-\hat{p}_i))$

将 $\mathrm{d}L/\mathrm{d}\hat{p}=(\mathrm{d}L/\mathrm{d}\hat{p}_1,\ldots,\mathrm{d}L/\mathrm{d}\hat{p}_n)^T$ 看作一个向量，计算出其结果并赋给变量 `d_l_a2`.

In [115]:
d_l_a2 = (a2-y)/(a2*(1-a2))
print(d_l_a2)

if d_l_a2.shape != a2.shape:
    print("Shapes do not match! Please redo the calculation.")


[[-0.00182416]
 [-0.01144566]
 [-0.00038462]
 [-0.00876071]]


`d_l_a2` 是损失函数对 $A_2$ 的“上游导数”，我们需要将其传播给下游 $Z_2$。由于 $A_2=\mathrm{sigmoid}(Z_2)$，根据课件中反向传播的规则1，可以得到下游导数为

$\mathrm{d}L/\mathrm{d}Z_2=\mathrm{d}L/\mathrm{d}A_2\circ \mathrm{sigmoid}'(Z_2)$，

其中 $\mathrm{sigmoid}'$ 是 Sigmoid 的导数，$\circ$ 是向量或矩阵的逐元素相乘。

In [91]:
d_l_z2 = d_l_a2 * d_sigmoid(z2)
print(d_l_z2)

if d_l_z2.shape != z2.shape:
    print("Shapes do not match! Please redo the calculation.")

[[-3.30944442e-06]
 [-1.28055021e-04]
 [-1.47818326e-07]
 [-7.47789527e-05]]


接下来，再将 $Z_2$ 的“上游导数”传给 $A_1$、$W_2$ 和 $b_2$。根据规则2，

$\mathrm{d}L/\mathrm{d}A_1=(\mathrm{d}L/\mathrm{d}Z_2)W_2^T$，

$\mathrm{d}L/\mathrm{d}W_2=A_1^T(\mathrm{d}L/\mathrm{d}Z_2)$，

$\mathrm{d}L/\mathrm{d}b_2=(\mathrm{d}L/\mathrm{d}Z_2)^T\mathbf{1}_n$。

请根据如上公式计算对应的导数，并赋值给相应的变量。

In [111]:
d_l_a1 = d_l_z2.dot(w2.T)
print("d_A1:\n", d_l_a1)

d_l_w2 = a1.T.dot(d_l_z2)
print("d_W2:\n", d_l_w2)

d_l_b2 = (d_l_z2.T).dot(ones)
print("d_b2:\n", d_l_b2)

if (d_l_a1.shape != a1.shape) or (d_l_w2.shape != w2.shape) or (d_l_b2.shape != b2.shape):
    print("Shapes do not match! Please redo the calculation.")


d_A1:
 [[ 1.43746141e-06 -7.30040301e-06 -7.23704702e-06 -3.32286057e-06 -1.27806242e-06]
 [ 5.56208615e-05 -2.82480422e-04 -2.80028938e-04 -1.28574143e-04 -4.94531073e-05]
 [ 6.42050786e-08 -3.26076893e-07 -3.23247060e-07 -1.48417567e-07 -5.70854272e-08]
 [ 3.24803335e-05 -1.64957141e-04 -1.63525573e-04 -7.50820989e-05 -2.88786145e-05]]
d_W2:
 [[-2.14714874e-04]
 [-2.69578683e-05]
 [-2.97879168e-04]
 [-1.62483280e-04]
 [-4.27826472e-05]]
d_b2:
 [[-0.00020629]]


请完成后续的过程，计算出 $\mathrm{d}L/\mathrm{d}W_1$ 和 $\mathrm{d}L/\mathrm{d}b_1$。

In [114]:
d_l_z1 = d_l_a1 * d_sigmoid(z1)
print(d_l_z1)

d_l_w1 = x.T.dot(d_l_z1)
print("d_W1:\n", d_l_w1)

d_l_b1 = (d_l_z1.T).dot(ones)
print("d_b1:\n", d_l_b1)

if (d_l_w1.shape != w1.shape) or (d_l_b1.shape != b1.shape):
    print("Shapes do not match! Please redo the calculation.")


[[ 3.20943449e-07 -1.82101417e-06 -1.08528702e-06 -7.51392277e-07 -3.04273094e-07]
 [ 1.10736801e-05 -1.94462574e-05 -5.34495307e-05 -2.91801194e-05 -8.27185694e-06]
 [ 8.01559564e-09 -6.69343118e-08 -4.00745429e-08 -1.39218473e-08 -1.11060494e-08]
 [ 8.09418044e-06 -2.42278457e-05 -2.68059054e-05 -1.55636142e-05 -3.29436632e-06]]
d_W1:
 [[ 8.10219604e-06 -2.42947800e-05 -2.68459800e-05 -1.55775360e-05 -3.30547237e-06]
 [ 1.91678606e-05 -4.36741031e-05 -8.02554361e-05 -4.47437336e-05 -1.15662233e-05]]
d_b1:
 [[ 1.94968196e-05]
 [-4.55620516e-05]
 [-8.13807977e-05]
 [-4.55090477e-05]
 [-1.18816024e-05]]


### 第5题

将第4题中的步骤封装成三个函数：`forward()` 计算正向传播结果，得到预测值向量 `phat`，`loss()` 计算整体损失函数值，`backward()` 计算反向传播后各参数的导数。

In [116]:
def forward(x, w1, b1, w2, b2):
    a0 = x
    ones = np.ones((n, 1))
    z1 = a0.dot(w1) + ones.dot(b1.T)
    a1 = softplus(z1)
    z2 = a1.dot(w2) + ones.dot(b2.T)
    a2 = sigmoid(z2)
    phat = a2
    print(phat)
    return z1, a1, z2, a2

def loss_function(y, phat):
    loss = (phat-y)/(phat*(1-phat))
    return loss

def backward(x, w1, b1, w2, b2, z1, a1, z2, a2, y):
    d_l_z2 = d_l_a2 * d_sigmoid(z2)
    d_l_a1 = d_l_z2.dot(w2.T)
    d_l_w2 = a1.T.dot(d_l_z2)
    d_l_b2 = (d_l_z2.T).dot(ones)
    d_l_z1 = d_l_a1 * d_sigmoid(z1)
    d_l_w1 = x.T.dot(d_l_z1)
    d_l_b1 = (d_l_z1.T).dot(ones)
    return d_l_w1, d_l_b1, d_l_w2, d_l_b2

与之前的结果互相印证：

In [117]:
x = np.array([[0.0, 0.0],
              [0.0, 1.0],
              [1.0, 0.0],
              [1.0, 1.0]])
y = np.array([[0.0],
              [1.0],
              [1.0],
              [0.0]])
p = 2
d = 1
n = 4
r = 5

np.random.seed(123)
w1 = np.random.normal(size=(p, r))
b1 = np.random.normal(size=(r, 1))
w2 = np.random.normal(size=(r, d))
b2 = np.random.normal(size=(d, 1))

z1, a1, z2, a2 = forward(x, w1, b1, w2, b2)
phat = a2
loss = loss_function(y, phat)
grads = backward(x, w1, b1, w2, b2, z1, a1, z2, a2, y)

print("phat =\n", phat)
print("loss =", loss)
print("(dw1, db1, dw2, db2) =\n", grads)

[[ 549.1969833 ]
 [  87.369357  ]
 [2599.97309354]
 [ 115.14603531]]
phat =
 [[ 549.1969833 ]
 [  87.369357  ]
 [2599.97309354]
 [ 115.14603531]]
loss = [[-0.00182416]
 [-0.01144566]
 [-0.00038462]
 [-0.00876071]]
(dw1, db1, dw2, db2) =
 (array([[ 8.10219604e-06, -2.42947800e-05, -2.68459800e-05, -1.55775360e-05, -3.30547237e-06],
       [ 1.91678606e-05, -4.36741031e-05, -8.02554361e-05, -4.47437336e-05, -1.15662233e-05]]), array([[ 1.94968196e-05],
       [-4.55620516e-05],
       [-8.13807977e-05],
       [-4.55090477e-05],
       [-1.18816024e-05]]), array([[-2.14714874e-04],
       [-2.69578683e-05],
       [-2.97879168e-04],
       [-1.62483280e-04],
       [-4.27826472e-05]]), array([[-0.00020629]]))


最后将这三步放在循环中，并利用梯度下降法拟合出 $x$ 和 $y$ 之间的函数关系。下面是一个完整的神经网络模型，我们可以修改隐藏层的维度。

In [118]:
x = np.array([[0.0, 0.0],
              [0.0, 1.0],
              [1.0, 0.0],
              [1.0, 1.0]])
y = np.array([[0.0],
              [1.0],
              [1.0],
              [0.0]])

n = x.shape[0]
p = x.shape[1]
d = y.shape[1]
r = 10

np.random.seed(123)
w1 = np.random.normal(size=(p, r))
b1 = np.random.normal(size=(r, 1))
w2 = np.random.normal(size=(r, d))
b2 = np.random.normal(size=(d, 1))

nepoch = 1000
learning_rate = 0.1

for i in range(nepoch):
    z1, a1, z2, a2 = forward(x, w1, b1, w2, b2)
    phat = a2
    loss = loss_function(y, phat)
    dw1, db1, dw2, db2 = backward(x, w1, b1, w2, b2, z1, a1, z2, a2, y)
    
    if i % 50 == 0:
        print(f"iteration {i}, loss = {loss}, prediction = {phat.squeeze()}")
        
    w1 = w1 - learning_rate * dw1
    b1 = b1 - learning_rate * db1
    w2 = w2 - learning_rate * dw2
    b2 = b2 - learning_rate * db2

[[5.14780976e-04]
 [3.24250638e-04]
 [2.94601507e-05]
 [9.50104717e-06]]
iteration 0, loss = [[ 1.00051505e+00]
 [-3.08403403e+03]
 [-3.39441577e+04]
 [ 1.00000950e+00]], prediction = [5.14780976e-04 3.24250638e-04 2.94601507e-05 9.50104717e-06]
[[5.14784053e-04]
 [3.24253825e-04]
 [2.94603044e-05]
 [9.50112346e-06]]
[[5.14787130e-04]
 [3.24257012e-04]
 [2.94604582e-05]
 [9.50119975e-06]]
[[5.14790208e-04]
 [3.24260198e-04]
 [2.94606120e-05]
 [9.50127605e-06]]
[[5.14793285e-04]
 [3.24263385e-04]
 [2.94607658e-05]
 [9.50135235e-06]]
[[5.14796363e-04]
 [3.24266573e-04]
 [2.94609196e-05]
 [9.50142865e-06]]
[[5.14799440e-04]
 [3.24269760e-04]
 [2.94610734e-05]
 [9.50150495e-06]]
[[5.14802518e-04]
 [3.24272947e-04]
 [2.94612272e-05]
 [9.50158125e-06]]
[[5.14805596e-04]
 [3.24276134e-04]
 [2.94613810e-05]
 [9.50165755e-06]]
[[5.14808673e-04]
 [3.24279321e-04]
 [2.94615348e-05]
 [9.50173386e-06]]
[[5.14811751e-04]
 [3.24282509e-04]
 [2.94616886e-05]
 [9.50181016e-06]]
[[5.14814829e-04]
 [3.24